name: octane-gg

include:
  - AppConstants.yml
  - AppExtension.yml
  - AppTheme.yml
  - Resources.yml
  # Tests
  - AppTests.yml
  # Scripts
  - SwiftLint.yml
  # Templates
  - _FrameworkTemplate.yml
  - _UnitTestTemplate.yml

settings:
  base:
    ENABLE_BITCODE: NO
    IPHONEOS_DEPLOYMENT_TARGET: '14.1'
  configs:
    release:
      ENABLE_BITCODE: YES

options:
  bundleIdPrefix: cosmik
  xcodeVersion: '12.1'
  deploymentTarget:
    iOS: 14.1
  generateEmptyDirectories: true
  findCarthageFrameworks: true

configs:
  Debug: debug
  Release: release

targets:
  octane-gg:
    type: application
    platform: iOS
    deploymentTarget: '14.1'
    settings:
      TARGETED_DEVICE_FAMILY: 1
    sources:
      - path: ../App
      - path: ../Resources/Fonts
      - path: ../Resources/Assets.xcassets
    dependencies:
      # Carthage
      - carthage: Alamofire
      - carthage: AlamofireImage
      - carthage: Moya
      - carthage: SkeletonView
      # Scripts
      - target: SwiftLint
      # Targets
      - target: AppTheme
      - target: AppConstants
      - target: Resources
      - target: AppExtension