name: octane-gg

include:
  # Tests
  # Scripts
  - SwiftLint.yml
  # Templates
  - _FrameworkTemplate.yml
  - _UnitTestTemplate.yml

options:
  bundleIdPrefix: cosmik
  xcodeVersion: '12.1'
  deploymentTarget:
    iOS: 14.1
  generateEmptyDirectories: true
  findCarthageFrameworks: true

configs:
  Debug: debug
  Release: release

targets:
  octane-gg:
    type: application
    platform: iOS
    deploymentTarget: '14.1'
    settings:
      TARGETED_DEVICE_FAMILY: 1
    sources:
      - path: ../Application
      - path: ../Resources
    dependencies:
      - carthage: Alamofire
      - carthage: AlamofireImage
      - carthage: Moya
      - target: SwiftLint